name: Integrations tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#-----------------------------------------------------------------------------------#
jobs:
  Flask:
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    
    - name: Install python dependencies
      working-directory: ./backend/Flask
      run: |
        python -m pip install --upgrade pip
        pip install pytest==7.1.2  requests==2.27.1
        pip install -r requirements.txt
    
    - name: Start testing
      run : pytest tests/test_flask.py -s
      
#-----------------------------------------------------------------------------------#
  FastAPI:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    
    - name: Install python dependencies
      working-directory: ./backend/FastAPI
      run: |
        python -m pip install --upgrade pip
        pip install pytest==7.1.2  requests==2.27.1
        pip install -r requirements.txt
    
    - name: Start testing
      run : pytest tests/test_fastapi.py -s

#-----------------------------------------------------------------------------------#
  Springboot:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest==7.1.2  requests==2.27.1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        working-directory: ./backend/Springboot
        run: mvn -B package --file pom.xml

      - name: Set up mysql
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql version: '8.0'
          mysql database: 'codedecode'
          mysql root password: 12345678
          mysql user: 'root'
          mysql password: 12345678

      - name: Start testing
        run : mvn spring-boot:run
        timeout-minutes: 5
        
